.TH ELKME 1 "JULY 2015" "elkme 0.2.3" "User Manuals"
.SH NAME
elkme \- the command-line sms interface

.SH SYNOPSIS
.B elkme.py [-h] [-v] [-q] [-f \fIfile\fB] [-t \fITO\fB] [-s \fISENDER\fB] [-u
\fI USERNAME\fB] [-p \fIPASSWORD\fB] [--saveconf] [-c \fICONFIGFILE\fB] [
\fImessage \fB[\fImessage ...\fB]]

.SH DESCRIPTION
.B elkme
is an application for sending text messages with the
command line using the 46elks API from https://46elks.com

.SH OPTIONS
.IP "-h, --help"
Show an overview of the features of elkme and then exits
.IP "-v, --verbose"
Show debug output, this will display advanced information about the query
to the user
.IP "-q, --quiet"
Avoids most, but not necessarily all, output
.IP "-f FILE, --file FILE"
Reads up to 160 characters from a file and sends it to the specified recipient
.IP "-t TO, --to TO"
Recipient of the text message. Is read from the configuration file if not
provided. Must be in the format +CCXXXXXXXX (i.e. +46700000000 and +1XXXXXXXXXX
are both legal, but 0700000000 or SE0700000000 is not)
.IP "-s SENDER, --sender SENDER, --from SENDER"
Specifies who is the sender of the message. You may either insert a string with
3-11 characters using only a-z, A-Z and 0-9 beginning with a letter or you may
use a number which is unlocked with your 46elks-account (either a number that
you have through 46elks or one that 46elks have authorized to your account)
.IP "-u USERNAME, --username USERNAME"
Your API username for 46elks which you can find in the 46elks dashboard
(this is not the same as the username which you use to login to 46elks with)
.IP "-p PASSWORD, --password PASSWORD"
Your API password for 46elks which is a secret key found in the
46elks dashboard that can be used to authenticate your API calls to the server
togheter with the API username. Make sure to keep your password a secret.
.IP --saveconf
Saves the current configuration to default location or the configuration 
location provided using \fI-c\fR if present.
This allows the user to save settings and not have to enter them every time
they run elkme.

\fBsaveconf\fR supports saving \fI--to\fR, \fI--sender\fR,
\fI--username\fR and \fI--password\fR

.IP "-c CONFIGFILE, --config CONFIGFILE"
Read settings from specified file instead of from ~/.elkme

.SH COPYRIGHT
Licensed under the MIT license.
Copyright (c) 2015 46elks AB <hello@46elks.com>

This tool is developed by Emil Tullstedt <emil@46elks.com> and has secret
elk superpowers.

.SH FILES
See \fBelkme(5)\fR 
