.TH TEXTME 5 "JUNE 2015" "textme 0.1.1a1" "User Manuals"
.SH NAME
.B textme
-- configuration file for the textme(1) application

.SH DESCRIPTION
The
.B textme
file contains information about authentication and default receiver/sender for
the
.B textme(1)
application. The file currently only supports sending and receiving text 
messages using the 46elks API and is in a .ini-like format.

The file has a header ``[46elks]'' followed by one or more of the following:

.RS
username
.br
password
.br
from
.br
to
.RE

These items each have a value which is separated from the value using ``=''
and a ``#'' indicates a comment.

.SH FILES
/etc/textme TODO
.br
~/.textme

.SH SEE ALSO
textme(1)
